name: Expo Build and Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build and update (Preview)
        if: github.event_name == 'pull_request'
        run: |
          eas build --platform all --profile preview --non-interactive --no-wait
          eas update --branch preview --message "Preview build from PR #${{ github.event.number }}"

      - name: Build and update (Production)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          eas build --platform all --profile production --non-interactive --no-wait
          eas update --branch production --message "Production build from commit ${{ github.sha }}"
